# Utiliser l'image de base Ubuntu 18.04
FROM ubuntu:18.04

# Mettre à jour les packages et installer les dépendances
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    libgl1-mesa-glx

# Copier les fichiers requirements.txt dans le conteneur
COPY requirements.txt /app/requirements.txt

# Installer les dépendances Python
RUN pip3 install --no-cache-dir -r /app/requirements.txt

# Copier le reste de l'application dans le conteneur
COPY . /app

# Changer le répertoire de travail
WORKDIR /app

# Exposer le port sur lequel l'application va s'exécuter
EXPOSE 8080

# Lancer l'application avec Gunicorn
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8080", "app:app"]
